### ISSUE TITLE
landmark_video.py

### ISSUE THREAD

**Issue by ZlaaM** [yinguobing/cnn-facial-landmark#27]
when i try to execute the ( landmark_video.py) , i get this error 
Traceback (most recent call last):
  File "C:\Users\HP\Anaconda3\envs\ten\lib\site-packages\tensorflow\python\client\session.py", line 1092, in _run
    subfeed, allow_tensor=True, allow_operation=False)
  File "C:\Users\HP\Anaconda3\envs\ten\lib\site-packages\tensorflow\python\framework\ops.py", line 3478, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\Users\HP\Anaconda3\envs\ten\lib\site-packages\tensorflow\python\framework\ops.py", line 3520, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'input_image_tensor:0' refers to a Tensor which does not exist. The operation, 'input_image_tensor', does not exist in the graph."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/drive G/CNN/cnn-facial-landmark-save_model_ok/landmark_video.py", line 106, in <module>
    main()
  File "E:/drive G/CNN/cnn-facial-landmark-save_model_ok/landmark_video.py", line 89, in main
    landmarks = detect_marks(face_img, sess, detection_graph)
  File "E:/drive G/CNN/cnn-facial-landmark-save_model_ok/landmark_video.py", line 28, in detect_marks
    feed_dict={'input_image_tensor:0': image_np})
  File "C:\Users\HP\Anaconda3\envs\ten\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\HP\Anaconda3\envs\ten\lib\site-packages\tensorflow\python\client\session.py", line 1095, in _run
    'Cannot interpret feed_dict key as Tensor: ' + e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: The name 'input_image_tensor:0' refers to a Tensor which does not exist. The operation, 'input_image_tensor', does not exist in the graph.

what is the problem ?????

**Comment by yinguobing** [comment]
Python is complaining about a missing node which is named 'input_image_tensor:0'. If you are using a frozen model, make sure this input node name is consistent with the one you used in the exporting process.

**Comment by abdou31** [comment]
@ZlaaM how did you get landmark_video.py ? can you share the script?
