### ISSUE TITLE
PermissionDeniedError Traceback (most recent call last)

### ISSUE THREAD

**Issue by indramal** [yinguobing/cnn-facial-landmark#28]
When I Run the landmark.py file it has given me following error message. How to solve this error? 

```
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/train', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000002A8609C2C88>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
WARNING:tensorflow:From C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:From <ipython-input-1-3205b076f1ee>:27: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From <ipython-input-1-3205b076f1ee>:39: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.conv2d instead.
WARNING:tensorflow:From <ipython-input-1-3205b076f1ee>:47: max_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.max_pooling2d instead.
WARNING:tensorflow:From <ipython-input-1-3205b076f1ee>:153: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From <ipython-input-1-3205b076f1ee>:160: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dense instead.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /train\model.ckpt.
---------------------------------------------------------------------------
PermissionDeniedError                     Traceback (most recent call last)
~\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

~\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320 

~\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408 

PermissionDeniedError: Failed to create a directory: /; Permission denied
	 [[{{node save/MergeV2Checkpoints}}]]

During handling of the above exception, another exception occurred:

PermissionDeniedError                     Traceback (most recent call last)
<ipython-input-1-3205b076f1ee> in <module>
    320 
    321 if __name__ == '__main__':
--> 322     tf.app.run()

~\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\platform\app.py in run(main, argv)
    123   # Call the main function, passing through any arguments
    124   # to the final program.
--> 125   _sys.exit(main(argv))
    126 

<ipython-input-1-3205b076f1ee> in main(unused_argv)
    297 
    298     if mode == tf.estimator.ModeKeys.TRAIN:
--> 299         estimator.train(input_fn=_train_input_fn, steps=200000)
    300 
    301         # Export result as SavedModel.

~\Anaconda3\envs\mainenv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py in train(self, input_fn, hooks, steps, max_steps, saving_listeners)
    356 
    357       saving_listeners = _check_listeners_type(saving_listeners)
--> 358       loss = self._train_model(input_fn, hooks, saving_listeners)
    359       logging.info('Loss for final step: %s.', loss)
    360       return self

~\Anaconda3\envs\mainenv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py in _train_model(self, input_fn, hooks, saving_listeners)
   1122       return self._train_model_distributed(input_fn, hooks, saving_listeners)
   1123     else:
-> 1124       return self._train_model_default(input_fn, hooks, saving_listeners)
   1125 
   1126   def _train_model_default(self, input_fn, hooks, saving_listeners):

~\Anaconda3\envs\mainenv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py in _train_model_default(self, input_fn, hooks, saving_listeners)
   1156       return self._train_with_estimator_spec(estimator_spec, worker_hooks,
   1157                                              hooks, global_step_tensor,
-> 1158                                              saving_listeners)
   1159 
   1160   def _train_model_distributed(self, input_fn, hooks, saving_listeners):

~\Anaconda3\envs\mainenv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py in _train_with_estimator_spec(self, estimator_spec, worker_hooks, hooks, global_step_tensor, saving_listeners)
   1401         save_summaries_steps=save_summary_steps,
   1402         config=self._session_config,
-> 1403         log_step_count_steps=log_step_count_steps) as mon_sess:
   1404       loss = None
   1405       any_step_done = False

~\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\training\monitored_session.py in MonitoredTrainingSession(master, is_chief, checkpoint_dir, scaffold, hooks, chief_only_hooks, save_checkpoint_secs, save_summaries_steps, save_summaries_secs, config, stop_grace_period_secs, log_step_count_steps, max_wait_secs, save_checkpoint_steps, summary_dir)
    506       session_creator=session_creator,
    507       hooks=all_hooks,
--> 508       stop_grace_period_secs=stop_grace_period_secs)
    509 
    510 

~\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\training\monitored_session.py in __init__(self, session_creator, hooks, stop_grace_period_secs)
    932     super(MonitoredSession, self).__init__(
    933         session_creator, hooks, should_recover=True,
--> 934         stop_grace_period_secs=stop_grace_period_secs)
    935 
    936 

~\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\training\monitored_session.py in __init__(self, session_creator, hooks, should_recover, stop_grace_period_secs)
    646         stop_grace_period_secs=stop_grace_period_secs)
    647     if should_recover:
--> 648       self._sess = _RecoverableSession(self._coordinated_creator)
    649     else:
    650       self._sess = self._coordinated_creator.create_session()

~\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\training\monitored_session.py in __init__(self, sess_creator)
   1120     """
   1121     self._sess_creator = sess_creator
-> 1122     _WrappedSession.__init__(self, self._create_session())
   1123 
   1124   def _create_session(self):

~\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\training\monitored_session.py in _create_session(self)
   1125     while True:
   1126       try:
-> 1127         return self._sess_creator.create_session()
   1128       except _PREEMPTION_ERRORS as e:
   1129         logging.info('An error was raised while a session was being created. '

~\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\training\monitored_session.py in create_session(self)
    810       # Inform the hooks that a new session has been created.
    811       for hook in self._hooks:
--> 812         hook.after_create_session(self.tf_sess, self.coord)
    813       return _CoordinatedSession(
    814           _HookedSession(self.tf_sess, self._hooks), self.coord,

~\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\training\basic_session_run_hooks.py in after_create_session(self, session, coord)
    566     self._summary_writer.add_meta_graph(meta_graph_def)
    567     # The checkpoint saved here is the state at step "global_step".
--> 568     self._save(session, global_step)
    569     self._timer.update_last_triggered_step(global_step)
    570 

~\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\training\basic_session_run_hooks.py in _save(self, session, step)
    597       l.before_save(session, step)
    598 
--> 599     self._get_saver().save(session, self._save_path, global_step=step)
    600     self._summary_writer.add_session_log(
    601         SessionLog(

~\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\training\saver.py in save(self, sess, save_path, global_step, latest_filename, meta_graph_suffix, write_meta_graph, write_state, strip_default_attrs)
   1169           model_checkpoint_path = sess.run(
   1170               self.saver_def.save_tensor_name,
-> 1171               {self.saver_def.filename_tensor_name: checkpoint_file})
   1172 
   1173         model_checkpoint_path = compat.as_str(model_checkpoint_path)

~\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    927     try:
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:
    931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1150     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1151       results = self._do_run(handle, final_targets, final_fetches,
-> 1152                              feed_dict_tensor, options, run_metadata)
   1153     else:
   1154       results = []

~\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1326     if handle is None:
   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1328                            run_metadata)
   1329     else:
   1330       return self._do_call(_prun_fn, handle, feeds, fetches)

~\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1346           pass
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 
   1350   def _extend_graph(self):

PermissionDeniedError: Failed to create a directory: /; Permission denied
	 [[node save/MergeV2Checkpoints (defined at C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py:1403) ]]

Caused by op 'save/MergeV2Checkpoints', defined at:
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\asyncio\base_events.py", line 438, in run_forever
    self._run_once()
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\asyncio\base_events.py", line 1451, in _run_once
    handle._run()
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
    ret = callback()
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tornado\gen.py", line 1233, in inner
    self.run()
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tornado\gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\ipykernel\kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\ipykernel\kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\ipykernel\kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\IPython\core\interactiveshell.py", line 2819, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\IPython\core\interactiveshell.py", line 2845, in _run_cell
    return runner(coro)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\IPython\core\async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\IPython\core\interactiveshell.py", line 3020, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\IPython\core\interactiveshell.py", line 3185, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\IPython\core\interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-3205b076f1ee>", line 322, in <module>
    tf.app.run()
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "<ipython-input-1-3205b076f1ee>", line 299, in main
    estimator.train(input_fn=_train_input_fn, steps=200000)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 358, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1124, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1158, in _train_model_default
    saving_listeners)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1403, in _train_with_estimator_spec
    log_step_count_steps=log_step_count_steps) as mon_sess:
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\training\monitored_session.py", line 508, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\training\monitored_session.py", line 934, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\training\monitored_session.py", line 648, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1122, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1127, in _create_session
    return self._sess_creator.create_session()
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\training\monitored_session.py", line 805, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\training\monitored_session.py", line 562, in create_session
    self._scaffold.finalize()
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\training\monitored_session.py", line 219, in finalize
    self._saver.build()
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\training\saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\training\saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\training\saver.py", line 504, in _build_internal
    save_tensor = self._AddShardedSaveOps(filename_tensor, per_device)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\training\saver.py", line 295, in _AddShardedSaveOps
    return self._AddShardedSaveOpsForV2(filename_tensor, per_device)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\training\saver.py", line 277, in _AddShardedSaveOpsForV2
    sharded_prefixes, checkpoint_prefix, delete_old_dirs=True)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 547, in merge_v2_checkpoints
    delete_old_dirs=delete_old_dirs, name=name)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

PermissionDeniedError (see above for traceback): Failed to create a directory: /; Permission denied
	 [[node save/MergeV2Checkpoints (defined at C:\Users\iHacker\Anaconda3\envs\mainenv\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py:1403) ]]

```

**Comment by yinguobing** [comment]
It looks like a system I/O error. Make sure you have provided correct file path for TensorFlow to write checkpoint files.
