### ISSUE TITLE
landmark.py

### ISSUE THREAD

**Issue by ZlaaM** [yinguobing/cnn-facial-landmark#58]

**Comment by SushantAhuja-AIML** [comment]
I am facing the same issue.

**Comment by ZlaaM** [comment]
@SushantAhuja-AIML  
Did you solve the problem?

**Comment by ZlaaM** [comment]
@yinguobing 
please, what is the problem ????

**Comment by ZlaaM** [comment]
@yinguobing 
Any version of Tenerife was used?
 when TensorFlow 1.13 is used the error was 
tensorflow.python.framework.errors_impl.InvalidArgumentError: Feature: label/marks (data type: float) is required but could not be found.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[node IteratorGetNext (defined at C:/Users/HP/PycharmProjects/CNN1_Last/landmark.py:134) ]]

**Comment by yinguobing** [comment]
Check your tfrecord file, make sure the feature named 'label/marks' exist.

**Comment by ZlaaM** [comment]
@yinguobing 

When I tried to configure the train. record,  I got this error 
Traceback (most recent call last):
  File "C:/Users/HP/PycharmProjects/CNN1_Last/tf_record.py", line 115, in <module>
    tf.app.run()
  File "C:\Users\HP\Anaconda3\envs\t\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:/Users/HP/PycharmProjects/CNN1_Last/tf_record.py", line 105, in main
    samples = pd.read_csv(FLAGS.csv)
  File "C:\Users\HP\Anaconda3\envs\t\lib\site-packages\pandas\io\parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\HP\Anaconda3\envs\t\lib\site-packages\pandas\io\parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\HP\Anaconda3\envs\t\lib\site-packages\pandas\io\parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "C:\Users\HP\Anaconda3\envs\t\lib\site-packages\pandas\io\parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\HP\Anaconda3\envs\t\lib\site-packages\pandas\io\parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'' does not exist: b''

please, what is the problem ?? 
thanks a lot

**Comment by ZlaaM** [comment]
@yinguobing 
When I tried to create the tfrecord  file , I encountered this problem!!


C:\Users\HP\Anaconda3\envs\t\lib\site-packages\h5py\__init__.py:72: UserWarning: h5py is running against HDF5 1.10.2 when it was built against 1.10.3, this may cause problems
  '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "C:\Users\HP\Anaconda3\envs\t\lib\site-packages\pandas\core\indexes\base.py", line 4381, in get_value
    return libindex.get_value_box(s, key)
  File "pandas\_libs\index.pyx", line 52, in pandas._libs.index.get_value_box
  File "pandas\_libs\index.pyx", line 48, in pandas._libs.index.get_value_at
  File "pandas\_libs\util.pxd", line 113, in pandas._libs.util.get_value_at
  File "pandas\_libs\util.pxd", line 98, in pandas._libs.util.validate_indexer
TypeError: 'str' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/HP/PycharmProjects/CNN1_Last/tf_record.py", line 117, in <module>
    tf.app.run()
  File "C:\Users\HP\Anaconda3\envs\t\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:/Users/HP/PycharmProjects/CNN1_Last/tf_record.py", line 109, in main
    sample_name = row['file_basename']
  File "C:\Users\HP\Anaconda3\envs\t\lib\site-packages\pandas\core\series.py", line 868, in __getitem__
    result = self.index.get_value(self, key)
  File "C:\Users\HP\Anaconda3\envs\t\lib\site-packages\pandas\core\indexes\base.py", line 4389, in get_value
    raise e1
  File "C:\Users\HP\Anaconda3\envs\t\lib\site-packages\pandas\core\indexes\base.py", line 4375, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas\_libs\index.pyx", line 81, in pandas._libs.index.IndexEngine.get_value
  File "pandas\_libs\index.pyx", line 89, in pandas._libs.index.IndexEngine.get_value
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'file_basename'

Process finished with exit code 1

**Comment by ZlaaM** [comment]
please what is the wrong !!!?
Traceback (most recent call last):
  File "C:/Users/HP/PycharmProjects/land_mark/generate_tf.py", line 102, in <module>
    tf.app.run()
  File "C:\Users\HP\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:/Users/HP/PycharmProjects/land_mark/generate_tf.py", line 92, in main
    samples = pd.read_csv(FLAGS.csv)
  File "C:\Users\HP\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\HP\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\HP\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "C:\Users\HP\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\HP\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'' does not exist

Process finished with exit code

**Comment by ZlaaM** [comment]
@yinguobing ????

**Comment by yinguobing** [comment]
Could you provide the command you used?

**Comment by ZlaaM** [comment]
@yinguobing 
"""
import json
import os
import pandas as pd
import tensorflow as tf
from tqdm import tqdm

tf.enable_eager_execution()


# FLAGS, used as interface of user inputs.
flags = tf.app.flags
flags.DEFINE_string('csv', '', 'the csv file contains all file to be encoded')
flags.DEFINE_string('image_dir', '', 'G:\\data1\\images')
flags.DEFINE_string('mark_dir', '', 'G:\\data1\\marks')
flags.DEFINE_string('output_file', 'record.record',
                    'Where the record file should be placed.')
FLAGS = flags.FLAGS


def _int64_feature(value):
    """Returns an int64_list from a bool / enum / int / uint."""
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))


def _float_feature(value):
    """Returns a float_list from a float / double."""
    return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))


def _float_feature_list(value):
    """Returns a float_list from a float / double."""
    return tf.train.Feature(float_list=tf.train.FloatList(value=value))


def _bytes_feature(value):
    """Returns a bytes_list from a string / byte."""
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))


def get_ibug_files(sample_name):
    """Generate sample files tuple"""
    image_file = os.path.join(FLAGS.image_dir, sample_name + '.jpg')
    mark_file = os.path.join(FLAGS.mark_dir, sample_name + '.json')
    return image_file, mark_file


def get_ibug_sample(image_file, mark_file):
    """Create a ibug sample from raw disk files."""
    # Keep the filename in the record for debug reasons.
    filename = image_file.split('/')[-1].split('.')[-2]
    ext_name = image_file.split('/')[-1].split('.')[-1]

    # Read encoded image file.
    with tf.gfile.GFile(image_file, 'rb') as fid:
        encoded_jpg = fid.read()

    # Read the marks from a json file.
    with open(mark_file) as fid:
        marks = json.load(fid)

    return {"filename": filename,
            "image_format": ext_name,
            "image": encoded_jpg,
            "marks": marks}


def create_tf_example(ibug_sample):
    """create TFRecord example from a data sample."""
    # Get required features ready.
    image_shape = tf.image.decode_jpeg(ibug_sample["image"]).shape

    # After getting all the features, time to generate a TensorFlow example.
    feature = {
        'image/height': _int64_feature(image_shape[0]),
        'image/width': _int64_feature(image_shape[1]),
        'image/depth': _int64_feature(image_shape[2]),
        'image/filename': _bytes_feature(ibug_sample['filename'].encode('utf8')),
        'image/encoded': _bytes_feature(ibug_sample['image']),
        'image/format': _bytes_feature(ibug_sample['image_format'].encode('utf8')),
        'label/marks': _float_feature_list(ibug_sample['marks'])
    }
    tf_example = tf.train.Example(features=tf.train.Features(feature=feature))

    return tf_example


def main(_):
    """Entrance"""
    tf_writer = tf.python_io.TFRecordWriter(FLAGS.output_file)

    samples = pd.read_csv(FLAGS.csv)
    for _, row in tqdm(samples.iterrows()):
        sample_name = row['file_basename']
        img_file, mark_file = get_ibug_files(sample_name)
        ibug_sample = get_ibug_sample(img_file, mark_file)
        tf_example = create_tf_example(ibug_sample)
        tf_writer.write(tf_example.SerializeToString())


if __name__ == '__main__':
    tf.app.run()

**Comment by ZlaaM** [comment]
`"""
import json
import os
import pandas as pd
import tensorflow as tf
from tqdm import tqdm

tf.enable_eager_execution()


# FLAGS, used as interface of user inputs.
flags = tf.app.flags
flags.DEFINE_string('csv', '', 'the csv file contains all file to be encoded')
flags.DEFINE_string('image_dir', '', 'G:\\data1\\images')
flags.DEFINE_string('mark_dir', '', 'G:\\data1\\marks')
flags.DEFINE_string('output_file', 'record.record',
                    'Where the record file should be placed.')
FLAGS = flags.FLAGS


def _int64_feature(value):
    """Returns an int64_list from a bool / enum / int / uint."""
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))


def _float_feature(value):
    """Returns a float_list from a float / double."""
    return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))


def _float_feature_list(value):
    """Returns a float_list from a float / double."""
    return tf.train.Feature(float_list=tf.train.FloatList(value=value))


def _bytes_feature(value):
    """Returns a bytes_list from a string / byte."""
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))


def get_ibug_files(sample_name):
    """Generate sample files tuple"""
    image_file = os.path.join(FLAGS.image_dir, sample_name + '.jpg')
    mark_file = os.path.join(FLAGS.mark_dir, sample_name + '.json')
    return image_file, mark_file


def get_ibug_sample(image_file, mark_file):
    """Create a ibug sample from raw disk files."""
    # Keep the filename in the record for debug reasons.
    filename = image_file.split('/')[-1].split('.')[-2]
    ext_name = image_file.split('/')[-1].split('.')[-1]

    # Read encoded image file.
    with tf.gfile.GFile(image_file, 'rb') as fid:
        encoded_jpg = fid.read()

    # Read the marks from a json file.
    with open(mark_file) as fid:
        marks = json.load(fid)

    return {"filename": filename,
            "image_format": ext_name,
            "image": encoded_jpg,
            "marks": marks}


def create_tf_example(ibug_sample):
    """create TFRecord example from a data sample."""
    # Get required features ready.
    image_shape = tf.image.decode_jpeg(ibug_sample["image"]).shape

    # After getting all the features, time to generate a TensorFlow example.
    feature = {
        'image/height': _int64_feature(image_shape[0]),
        'image/width': _int64_feature(image_shape[1]),
        'image/depth': _int64_feature(image_shape[2]),
        'image/filename': _bytes_feature(ibug_sample['filename'].encode('utf8')),
        'image/encoded': _bytes_feature(ibug_sample['image']),
        'image/format': _bytes_feature(ibug_sample['image_format'].encode('utf8')),
        'label/marks': _float_feature_list(ibug_sample['marks'])
    }
    tf_example = tf.train.Example(features=tf.train.Features(feature=feature))

    return tf_example


def main(_):
    """Entrance"""
    tf_writer = tf.python_io.TFRecordWriter(FLAGS.output_file)

    samples = pd.read_csv(FLAGS.csv)
    for _, row in tqdm(samples.iterrows()):
        sample_name = row['file_basename']
        img_file, mark_file = get_ibug_files(sample_name)
        ibug_sample = get_ibug_sample(img_file, mark_file)
        tf_example = create_tf_example(ibug_sample)
        tf_writer.write(tf_example.SerializeToString())


if __name__ == '__main__':
    tf.app.run()`

**Comment by ZlaaM** [comment]
"""
import json
import os
import pandas as pd
import tensorflow as tf
from tqdm import tqdm

tf.enable_eager_execution()


# FLAGS, used as interface of user inputs.
flags = tf.app.flags
flags.DEFINE_string('csv', '', 'the csv file contains all file to be encoded')
flags.DEFINE_string('image_dir', '', 'G:\\data1\\images')
flags.DEFINE_string('mark_dir', '', 'G:\\data1\\marks')
flags.DEFINE_string('output_file', 'record.record',
                    'Where the record file should be placed.')
FLAGS = flags.FLAGS


def _int64_feature(value):
    """Returns an int64_list from a bool / enum / int / uint."""
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))


def _float_feature(value):
    """Returns a float_list from a float / double."""
    return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))


def _float_feature_list(value):
    """Returns a float_list from a float / double."""
    return tf.train.Feature(float_list=tf.train.FloatList(value=value))


def _bytes_feature(value):
    """Returns a bytes_list from a string / byte."""
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))


def get_ibug_files(sample_name):
    """Generate sample files tuple"""
    image_file = os.path.join(FLAGS.image_dir, sample_name + '.jpg')
    mark_file = os.path.join(FLAGS.mark_dir, sample_name + '.json')
    return image_file, mark_file


def get_ibug_sample(image_file, mark_file):
    """Create a ibug sample from raw disk files."""
    # Keep the filename in the record for debug reasons.
    filename = image_file.split('/')[-1].split('.')[-2]
    ext_name = image_file.split('/')[-1].split('.')[-1]

    # Read encoded image file.
    with tf.gfile.GFile(image_file, 'rb') as fid:
        encoded_jpg = fid.read()

    # Read the marks from a json file.
    with open(mark_file) as fid:
        marks = json.load(fid)

    return {"filename": filename,
            "image_format": ext_name,
            "image": encoded_jpg,
            "marks": marks}


def create_tf_example(ibug_sample):
    """create TFRecord example from a data sample."""
    # Get required features ready.
    image_shape = tf.image.decode_jpeg(ibug_sample["image"]).shape

    # After getting all the features, time to generate a TensorFlow example.
    feature = {
        'image/height': _int64_feature(image_shape[0]),
        'image/width': _int64_feature(image_shape[1]),
        'image/depth': _int64_feature(image_shape[2]),
        'image/filename': _bytes_feature(ibug_sample['filename'].encode('utf8')),
        'image/encoded': _bytes_feature(ibug_sample['image']),
        'image/format': _bytes_feature(ibug_sample['image_format'].encode('utf8')),
        'label/marks': _float_feature_list(ibug_sample['marks'])
    }
    tf_example = tf.train.Example(features=tf.train.Features(feature=feature))

    return tf_example


def main(_):
    """Entrance"""
    tf_writer = tf.python_io.TFRecordWriter(FLAGS.output_file)

    samples = pd.read_csv(FLAGS.csv)
    for _, row in tqdm(samples.iterrows()):
        sample_name = row['file_basename']
        img_file, mark_file = get_ibug_files(sample_name)
        ibug_sample = get_ibug_sample(img_file, mark_file)
        tf_example = create_tf_example(ibug_sample)
        tf_writer.write(tf_example.SerializeToString())


if __name__ == '__main__':
    tf.app.run()

**Comment by ZlaaM** [comment]
@yinguobing

**Comment by yinguobing** [comment]
I mean, how do you run this script file? Please provide the command you typed in the terminal window.

**Comment by ZlaaM** [comment]
I use the text editor (pycharm) and don't execute using the terminal window.

**Comment by yinguobing** [comment]
Please follow the instructions in the README.md.

**Comment by abdou31** [comment]
I have faced the same problem, did you solve it?

**Comment by saaquib-pro** [comment]
I am facing the same issue. can you please help me on this? 
And also can you provide the path from where i can download the  dataset (tf record files) for training.

**Comment by abdou31** [comment]
I fixed the problem by changing `labels\marks` with `labels\points` in `landmark.py`

**Comment by saaquib-pro** [comment]
Thank you. It helped me and I'm able to train the model.

**Comment by ZlaaM** [comment]
@abdou31 
by using which version of tensorflow?

**Comment by ZlaaM** [comment]
@abdou31

**Comment by abdou31** [comment]
@ZlaaM 
I used:
+ Tensorflow 1.13.1
+ Python 3.6

**Comment by ZlaaM** [comment]
thanks 
Windows 10 64 bit? cpu version ?

**Comment by ZlaaM** [comment]
@abdou31 
thanks
Windows 10 64 bit? cpu version ?
and which version of numpy ?

**Comment by abdou31** [comment]
for numpy, I cannot remember the version but others 
I have used: Windows 10 x64 , gpu version

**Comment by ZlaaM** [comment]
@abdou31  
thanks
